FROM node AS build
WORKDIR /app
COPY package.json .
RUN npm install
COPY . .

ENV REACT_APP_API_HOST=api.battlestats.site

RUN npm run build

FROM nginx
COPY --from=build /app/build /usr/share/nginx/html