FROM node AS build
WORKDIR /app
COPY package.json .
RUN npm install
COPY . .

ENV REACT_APP_API_HOST=https://api.battlestats.menuhwang.com

RUN npm run build

FROM nginx
COPY --from=build /app/build /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
COPY ./default.conf /etc/nginx/conf.d/default.conf