name: Docker Build

on:
  push:
    branches:
      - main

  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  docker-build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Docker Login
        uses: docker/login-action@v1.12.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Build
        run: docker build -f Dockerfile.prod -t ${{ env.REGISTRY }}/${{ github.repository }} .

      - name: Docker push
        run: docker push -a ${{ env.REGISTRY }}/${{ github.repository }}
